[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput --settings=edumore360.settings_prod && python manage.py migrate --noinput --settings=edumore360.settings_prod"

[deploy]
startCommand = "gunicorn minimal_wsgi:application --env DJANGO_SETTINGS_MODULE=edumore360.settings_prod --log-level debug --timeout 120 --workers 1"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "edumore360.settings_prod"
PORT = "8000"
DATABASE_URL = "postgresql://neondb_owner:npg_R5dEIG2wvtSl@ep-soft-violet-a58sv217-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
