[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn edumore360.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "edumore360.settings_prod"
PORT = "8000"
