# Generated by Django 5.0.6 on 2025-05-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='smtp_password',
            field=models.CharField(default='your_new_app_password', max_length=100),
        ),
    ]
