# Generated by Django 5.0.6 on 2025-05-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemconfiguration_default_from_email_and_more'),
        ('core', '0004_update_email_settings'),
    ]

    operations = [
    ]
