# Generated by Django 5.0.6 on 2025-05-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250512_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='smtp_password',
            field=models.CharField(default='sipvehpgwtbwkesc', max_length=100),
        ),
    ]
