# Generated by Django 5.0.6 on 2025-05-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemconfiguration_smtp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_from_email',
            field=models.EmailField(default='skillnetservices@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='smtp_password',
            field=models.CharField(default='tdms ckdk tmgo fado', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='smtp_username',
            field=models.CharField(default='skillnetservices@gmail.com', max_length=100),
        ),
    ]
