# Generated by Django 5.0.6 on 2025-05-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_systemconfiguration_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='quiz_feedback_time',
            field=models.PositiveIntegerField(default=7, help_text='Time in seconds to show feedback after answering a quiz question'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='quiz_randomize_choices',
            field=models.BooleanField(default=True, help_text='Randomize the order of choices in multiple-choice questions'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='quiz_randomize_questions',
            field=models.BooleanField(default=True, help_text='Randomize the order of questions in quizzes'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='quiz_show_immediate_feedback',
            field=models.BooleanField(default=True, help_text='Show immediate feedback after answering a quiz question'),
        ),
    ]
