# Generated by Django 5.0.6 on 2025-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemconfiguration_quiz_feedback_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_test_mode',
            field=models.BooleanField(default=True, help_text='Process payments in test mode'),
        ),
    ]
