# Generated by Django 5.0.6 on 2025-05-15 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='scheduled_change_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('change_billing', 'Change Billing Cycle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
