# Generated by Django 5.0.6 on 2025-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on this question in seconds'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='timed_out',
            field=models.BooleanField(default=False, help_text='Whether the user ran out of time for this question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='per_question_time',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in seconds per question (default: 30 seconds)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_count',
            field=models.PositiveIntegerField(default=40, help_text='Number of questions to include in the quiz (default: 40)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='randomize_choices',
            field=models.BooleanField(default=True, help_text='Randomize the order of answer choices'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Randomize the order of questions'),
        ),
    ]
