# Generated by Django 5.0.6 on 2025-05-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_time_limit_questionattempt_time_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('general', 'General Quiz'), ('topic', 'Topic-Based Quiz'), ('practice', 'Practice Exam')], default='general', max_length=10),
        ),
    ]
