# Generated by Django 5.0.6 on 2025-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_immediate_feedback',
            field=models.BooleanField(default=True, help_text='Show immediate feedback after each question'),
        ),
    ]
