# Generated by Django 5.0.6 on 2025-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_explanation_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured quizzes are shown on the home page'),
        ),
    ]
