# Generated by Django 5.0.6 on 2025-05-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='If checked, users will be able to download the PDF document'),
        ),
        migrations.AddField(
            model_name='note',
            name='pdf_document',
            field=models.FileField(blank=True, help_text='Upload a PDF document for this note', null=True, upload_to='notes/pdfs/'),
        ),
    ]
