# Generated by Django 5.0.6 on 2025-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_note_allow_download_note_pdf_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='doc_document',
            field=models.FileField(blank=True, help_text='Upload a Word document for this note', null=True, upload_to='notes/docs/'),
        ),
        migrations.AddField(
            model_name='note',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from uploaded documents'),
        ),
        migrations.AddField(
            model_name='note',
            name='file_type',
            field=models.CharField(choices=[('none', 'No File'), ('pdf', 'PDF Document'), ('ppt', 'PowerPoint Presentation'), ('doc', 'Word Document'), ('other', 'Other Document')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='other_document',
            field=models.FileField(blank=True, help_text='Upload any other document for this note', null=True, upload_to='notes/others/'),
        ),
        migrations.AddField(
            model_name='note',
            name='ppt_document',
            field=models.FileField(blank=True, help_text='Upload a PowerPoint presentation for this note', null=True, upload_to='notes/ppts/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='If checked, users will be able to download the document'),
        ),
    ]
